spring:
  datasource:
    url: jdbc:h2:mem:lottery
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true

custom:
  random:
    url: https://www.random.org/integers/?num=1&min={min}&max={max}&col=1&base=10&format=plain&rnd=new
